version: '3.9'
services:
  app:
    build:
      context: .
    command: npm run start:deploy
    environment:
      MAIL_HOST: smtp.office365.com
      MAIL_PORT: 587
      MAIL_USER: contato.azulciano@outlook.com
      MAIL_PASS: essaeumasenhabemforte123
      REDIS_HOST: redis
      REDIS_PORT: 6379
      DATABASE_HOST: postgres
      DATABASE_PORT: 5432
      DATABASE_USER: postgres
      DATABASE_PASS: password
    ports:
      - "3000:3000"
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_started
    volumes:
      - .:/app
  
  redis:
    image: redis
    ports:
      - "6379:6379"
  
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 5s
      timeout: 5s
      retries: 3
    ports:
      - "5432:5432"